version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
      - ./apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "8088:80"
    depends_on:
      - db
    networks:
      - app-network
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: mini_classroom
      DB_USER: postgres
      DB_PASSWORD: secret123

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: mini_classroom
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret123
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
